import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Staff Managmenyt App By ShanthiBhavan",
  description: "Generated by create next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-black">
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <nav className="flex justify-between items-center p-4 bg-white text-white dark:bg-black">
              <div>
                <img src={"/logo.png"} alt="logo_" width={100} height={100} />
              </div>

              <div>
                <ul className="space-x-1 hidden md:flex">
                  <li className="bg-zinc-100 text-black py-1 px-2 rounded-full text-sm">
                    Home
                  </li>
                  <li className="bg-zinc-100 text-black py-1 px-2 rounded-full text-sm">
                    About
                  </li>
                  <li className="bg-zinc-100 text-black py-1 px-2 rounded-full text-sm">
                    Contact
                  </li>
                </ul>
              </div>

              <div>
                <button className="bg-black py-1 px-4 rounded-full">
                  Login
                </button>
              </div>
            </nav>
            <main>{children}</main>
            <ToastContainer />
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
