version: '3.3'

networks:
  shanthibhavan_staffs:
services:
  mongodb:
    container_name: sb_staffs_mongo
    image: mongo:6.0
    volumes:
      - ../sb-staff-mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sb_user
      - MONGO_INITDB_ROOT_PASSWORD=sb_password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - shanthibhavan_staffs